---
# tasks file for mongoDB setup

- hosts: ec2
  become: true
  
  tasks:
    - name: Install aptitude using apt
      apt: 
        name: aptitude 
        state: latest 
        update_cache: yes 
    
    - name: MongoDB - Import public key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
    
    - name: MongoDB - Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-4.4.list'
        repo: 'deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.4 multiverse'
        state: present
        update_cache: yes
    
    - name: install mongoDB
      apt: 
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Ensure mongodb is running and and enabled to start automatically on reboots
      systemd:
        name: mongodb
        enabled: yes
        state: started
